
import type { Metadata } from "next";
import ClientLayout from "../../_components/layout/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientLayout>
      {children}
    </ClientLayout>
  );
}
// http://localhost:3000/home => http://localhost:3000
// http://localhost:3000/ => http://localhost:3000

// config router